version: '3.9'
services:
  coffee-app:
    container_name: coffee-app
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=database
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - database
      - rabbitmq
  
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672' # RabbitMQ management UI

volumes:
  pgdata: {}
